version: "2.4"

services:

  dev:
    image: 16nsk/devcontainers
    command: sleep infinity
    ports:
      - "${APP_PORT:-8000}:8000"
    cpu_count: 2
    mem_limit: 4000000000
    mem_swappiness: 0

  # mariadb:
  #   image: mariadb:10
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=developer
  #     - MYSQL_USER=developer
  #     - MYSQL_PASSWORD=developer
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   ports:
  #     - "${FORWARD_DB_PORT:-3306}:3306"
  #   cpu_count: 1
  #   mem_limit: 1000000000
  #   mem_swappiness: 0

  # postgres:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_PASSWORD=developer
  #     - POSTGRES_USER=developer
  #     - POSTGRES_DB=developer
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   ports:
  #     - "${FORWARD_DB_PORT:-5432}:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   cpu_count: 1
  #   mem_limit: 1000000000
  #   mem_swappiness: 0
  
  # This is Postgresql with Postgis preenabled
  # postgis:
  #   image: postgis/postgis:13-3.0-alpine
  #   environment:
  #     - POSTGRES_PASSWORD=developer
  #     - POSTGRES_USER=developer
  #     - POSTGRES_DB=developer
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   ports:
  #     - "${FORWARD_DB_PORT:-5432}:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   cpu_count: 1
  #   mem_limit: 1000000000
  #   mem_swappiness: 0

  # mongo:
  #   image: mongo:4
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=developer
  #   ports:
  #     - "${FORWARD_MONGO_PORT:-27017}:27017"
  #   volumes:
  #     - mongo:/data/db
  #   cpu_count: 1
  #   mem_limit: 1000000000
  #   mem_swappiness: 0

  # elasticsearch:
  #   image: elasticsearch:7.12.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "${FORWARD_DB_PORT:-9200}:9200"
  #   volumes:
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   cpu_count: 1
  #   mem_limit: 1000000000
  #   mem_swappiness: 0
  
  # redis:
  #   image: redis:6-alpine
  #   cpu_count: 1
  #   mem_limit: 500000000
  #   mem_swappiness: 0
  
  # memcached:
  #   image: memcached:1-alpine
  #   cpu_count: 1
  #   mem_limit: 500000000
  #   mem_swappiness: 0
  
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "${FORWARD_MAILHOG_PORT:-8025}:8025"
  #   cpu_count: 1
  #   mem_limit: 500000000
  #   mem_swappiness: 0

  # minio:
  #   image: minio/minio
  #   environment:
  #     - MINIO_ACCESS_KEY=minio
  #     - MINIO_SECRET_KEY=minio123
  #   command: minio server /data
  #   ports:
  #     - "${FORWARD_MINIO_PORT:-9000}:9000"
  #   volumes:
  #     - minio:/data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   cpu_count: 1
  #   mem_limit: 1000000000
  #   mem_swappiness: 0

  # adminer:
  #   image: adminer
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=mariadb
  #   ports:
  #     - "${FORWARD_ADMINER_PORT:-8080}:8080"
  #   cpu_count: 1
  #   mem_limit: 500000000
  #   mem_swappiness: 0

volumes:
  projects:
  user:
  # mysql:
  # postgres:
  # mongo:
  # elasticsearch:
  # minio:
