name: buildx

on:
  push:
    branches: master
    tags: '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -  
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          if [ "$GITHUB_REF" != "refs/heads/master" ]; then
              export TAG=$GITHUB_REF
          fi
          echo $TAG
          cat <<'EOF' > docker-bake.hcl
          variable "TAG" {
              default=""
          }

          group "default" {
              targets = [
                  "7.4-14",
                  "8.0-16",
              ]
          }

          target "default" {
              context="."
              dockerfile="Dockerfile"
              platforms = [
                  "linux/amd64",
                  "linux/arm64"
              ]
          }
          
          target "7.4-14" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:7.4",
                  notequal("",TAG) ? "16nsk/devcontainers:7.4-${TAG}": "",
              ]
              args = {
                  PHP_VERSION="7.4",
                  NODE_VERSION="14",
              }
          }
          
          target "8.0-16" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:latest",
                  "16nsk/devcontainers:8.0",
                  notequal("",TAG) ? "16nsk/devcontainers:8.0-${TAG}": "",
              ]
              args = {
                  PHP_VERSION="8.0",
                  NODE_VERSION="16"
              }
          }
          EOF
          cat docker-bake.hcl
#       -
#         name: Build and push
#         uses: docker/bake-action@master
#         with:
#           push: true
#           files: docker-bake.hcl
