name: buildx

on:
  push:
    branches: develop

jobs:
  buildx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -  
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          cat <<'EOF' > docker-bake.hcl
          group "default" {
              targets = [
                  "8.0-16",
                  "7.4-14",
              ]
          }

          target "default" {
              context="."
              dockerfile="Dockerfile"
              platforms = [
                  "linux/amd64",
              ]
          }
          
          target "8.0-16" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:8.0-16-dev",
              ]
              args = {
                  PHP_VERSION="8.0",
                  NODE_VERSION="16"
              }
          }
          
          target "7.4-14" {
              inherits=["default"]
              tags = [
                  "16nsk/devcontainers:7.4-14-dev",
              ]
              args = {
                  PHP_VERSION="7.4",
                  NODE_VERSION="14",
              }
          }
          EOF
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          files: docker-bake.hcl
