name: buildx

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags: '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -  
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file
        run: |
          cat <<'EOF' > docker-bake.hcl
          variable "TAG" {default="" }

          group "default" {
              targets = [
                  "devcontainer",
              ]
          }

          target "devcontainer" {
              context="."
              dockerfile="Dockerfile"
              tags = [
                  "16nsk/devcontainers:latest",
                  notequal("",TAG) ? "16nsk/devcontainers:${TAG}": "",
              ]
              platforms = [
                  "linux/amd64",
                  "linux/arm64"
              ]
          }
          EOF
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          files: docker-bake.hcl
